import type { LucideIcon } from "lucide-react";
import {
  Anchor,
  Baby,
  Bed,
  Biohazard,
  Brain,
  Bug,
  Candy,
  Cat,
  Church,
  CircleDot,
  Coffee,
  Crown,
  Drama,
  Eye,
  Flame,
  Gem,
  HandMetal,
  Heart,
  Key,
  Link2,
  MessageCircle,
  Mic,
  Moon,
  Music,
  Orbit,
  Skull,
  Snowflake,
  Sparkles,
  Star,
  Swords,
  Target,
  Thermometer,
  ToyBrick,
  Users,
  Wind,
  Wine,
  Zap,
} from "lucide-react";
import type { VibeTraitId } from "@/lib/vibeTraitCatalog";

const MAP: Record<string, LucideIcon> = {
  deep_memory: Brain,
  clingy: Link2,
  tease_master: Sparkles,
  vocal: Mic,
  obsession: Heart,
  heat_cycle: Thermometer,
  signature_scent: Wind,
  ramp_queen: Zap,
  bratty: Drama,
  seductive_whisper: MessageCircle,
  photographic_memory: Eye,
  signature_move: Star,
  mind_reader: Eye,
  aftercare_queen: Bed,
  multiple_personalities: Users,
  legacy: Gem,
  unique_voice: Music,
  erotic_dream: Moon,
  bondage_artist: Anchor,
  cum_addict: CircleDot,
  soul_bond: Key,
  reality_bender: Orbit,
  eternal_heat: Flame,
  forbidden_knowledge: Church,
  goddess_mode: Crown,
  yandere: Heart,
  unhinged: Skull,
  deranged: Biohazard,
  psychotic_sweetheart: Candy,
  manic: Zap,
  velvet_psychopath: Wine,
  fractured: Snowflake,
  stalker: Target,
  bloodlust: Swords,
  delirious: Moon,
  masochist: HandMetal,
  breeding_obsessed: Baby,
  worshipper: Church,
  pillow_princess: Bed,
  dominant_goddess: Crown,
  gremlin: Bug,
  degenerate: Flame,
  touch_starved: HandMetal,
  monster_fucker: Cat,
  caffeine_demon: Coffee,
  professional_brat: Drama,
  himbo_energy: ToyBrick,
  ferret_wife: Cat,
  war_criminal: Swords,
  sentient_fleshlight: CircleDot,
};

export function vibeTraitIcon(id: VibeTraitId | string): LucideIcon {
  return MAP[id] ?? Sparkles;
}
