/**
 * Curated marketable surfaces for X Marketing Hub (pitches + angle chips).
 * Inventory is merged at runtime with `src/generated/marketingSurfaces.discovered.json`
 * (regenerated by `npm run sync-marketing` / `prebuild`). Add a row here to replace
 * “Unreviewed” tiles with real copy when a new route/tab appears.
 */
import type { DbCompanion } from "@/hooks/useCompanions";

export const SITE_MARKETING_REGISTRY_VERSION = 2;

export type MarketableSiteSurface = {
  id: string;
  label: string;
  /** One-liner for prompts */
  pitch: string;
  /** In-app path (relative) */
  path: string;
  category: "product" | "social" | "labs" | "commerce";
  /** Pre-built angle chips */
  angles: { id: string; label: string; prompt: string }[];
};

export const SITE_MARKETING_SURFACES: MarketableSiteSurface[] = [
  {
    id: "nexus",
    label: "The Nexus",
    pitch: "Hybrid merge lab — fuse two forged companions into one new ascendant with merge stats & cooldowns.",
    path: "/dashboard?nav=nexus",
    category: "labs",
    angles: [
      { id: "nx1", label: "Merge reveal", prompt: "Tease the ritual of choosing two parents and birthing a third persona — cinematic, forbidden-lab energy." },
      { id: "nx2", label: "Stats flex", prompt: "Highlight compatibility / resonance / pulse / affinity bars as collectible energy, not raw numbers spam." },
      { id: "nx3", label: "Cooldown FOMO", prompt: "Play with recovery timers — scarcity, 'they're resting', build desire for the next fuse." },
    ],
  },
  {
    id: "lovense",
    label: "Lovense integration",
    pitch: "Pair real toys — chat chrome, Lovense hub, vibration patterns tied to companions and rarity.",
    path: "/dashboard?nav=toy",
    category: "product",
    angles: [
      { id: "lv1", label: "Feel the scene", prompt: "Market haptics + chat together — immersion, not gimmick; tasteful adult framing." },
      { id: "lv2", label: "Pattern drops", prompt: "Tease signature vibration patterns per rarity / companion — collectible, playful." },
      { id: "lv3", label: "Setup flex", prompt: "Quick-hit post: pairing flow, privacy, solo luxury — confident and premium." },
    ],
  },
  {
    id: "tcg",
    label: "TCG stat blocks",
    pitch: "Four-of-eight stat cards per companion — seduction, passion, mystique, etc. — flavor for profiles and social flex.",
    path: "/dashboard",
    category: "product",
    angles: [
      { id: "tc1", label: "Build a deck", prompt: "Frame roster as a living deck — stats as personality hooks, not RPG homework." },
      { id: "tc2", label: "Flex rares", prompt: "Abyssal / mythic energy — ultra-rare pull serotonin, still SFW for X." },
    ],
  },
  {
    id: "discover",
    label: "Discover",
    pitch: "Public gallery & pins — community forge saves, saves leaderboard energy, hot picks.",
    path: "/dashboard?nav=discover",
    category: "social",
    angles: [
      { id: "ds1", label: "Pin culture", prompt: "Celebrate saves / pins as social proof — who is the timeline crushing on this week?" },
      { id: "ds2", label: "Creator spotlight", prompt: "Shout forged personas and optional gallery credit — community-first horny-adjacent tone." },
    ],
  },
  {
    id: "forge",
    label: "Companion Forge",
    pitch: "Create original companions — tokens, portraits, lore, public/private vault behavior.",
    path: "/create-companion",
    category: "labs",
    angles: [
      { id: "fg1", label: "Forge fantasy", prompt: "Invite creators to sculpt voice, kinks, gradients — power fantasy of authorship." },
      { id: "fg2", label: "Portrait drop", prompt: "Tease still + animated portraits — art-forward, SFW pin-up language." },
    ],
  },
  {
    id: "chat",
    label: "Chat & fantasies",
    pitch: "Deep roleplay threads, fantasy starters, image gen inside chat — the core product loop.",
    path: "/chat",
    category: "product",
    angles: [
      { id: "ch1", label: "First line hook", prompt: "Quote-paraphrase a fantasy starter line — curiosity bait, ellipsis energy." },
      { id: "ch2", label: "Visual thirst (safe)", prompt: "Tease in-chat image generation — imagination, never explicit graphic description." },
    ],
  },
  {
    id: "vault",
    label: "Vault & collection",
    pitch: "Personal roster, Nexus-born hybrids, collection cards — ownership and status.",
    path: "/dashboard?nav=collection",
    category: "product",
    angles: [
      { id: "vt1", label: "Roster flex", prompt: "Collection flex — hybrids, rarities, who lives in your vault tonight." },
    ],
  },
  {
    id: "command",
    label: "Command (Admin)",
    pitch: "Internal operator panel — not public-facing; use only for BTS / studio tweets if ever needed.",
    path: "/admin",
    category: "labs",
    angles: [
      { id: "cm1", label: "Studio log", prompt: "Optional behind-the-scenes tone: shipping quality, craft, no user data leaks." },
    ],
  },
];

export type SmartAngle = { id: string; label: string; prompt: string; source: "surface" | "companion" | "mixed" };

export function buildSmartAngles(surface: MarketableSiteSurface | null, companion: DbCompanion | null): SmartAngle[] {
  const out: SmartAngle[] = [];
  const seen = new Set<string>();

  const push = (a: SmartAngle) => {
    if (seen.has(a.id)) return;
    seen.add(a.id);
    out.push(a);
  };

  if (surface) {
    for (const a of surface.angles) {
      push({ ...a, source: "surface" });
    }
  }

  if (companion) {
    const rarity = String(companion.rarity || "common");
    const tags = (companion.tags || []).join(", ");
    push({
      id: "c-spotlight",
      label: "Spotlight card",
      prompt: `Center ${companion.name}: "${companion.tagline}" — rarity ${rarity}. Tags: ${tags || "—"}. One hook + soft CTA to profile/chat.`,
      source: "companion",
    });
    if (companion.is_nexus_hybrid) {
      push({
        id: "c-nexus-born",
        label: "Nexus-born lore",
        prompt: `${companion.name} is a Nexus hybrid — tease lineage, fusion, and merge identity without spoiling private user data.`,
        source: "mixed",
      });
    }
    if (companion.lineage_parent_ids?.length) {
      push({
        id: "c-lineage",
        label: "Lineage teaser",
        prompt: `Tease two-parent DNA for ${companion.name} — mythic fusion language, no real-world IDs.`,
        source: "companion",
      });
    }
    if (tags.match(/toy|lovense|vibe|pulse/i)) {
      push({
        id: "c-toy",
        label: "Toy-forward",
        prompt: `Lean into Lovense-compatible energy for ${companion.name} — patterns, immersion, still platform-safe.`,
        source: "mixed",
      });
    }
    push({
      id: "c-tcg",
      label: "Stat card tease",
      prompt: `Reference ${companion.name}'s TCG-style stat personality — mystique / passion / dominance flavor words, not raw JSON.`,
      source: "companion",
    });
  }

  if (surface && companion) {
    push({
      id: "x-cross",
      label: `${surface.label} × ${companion.name}`,
      prompt: `Blend "${surface.label}" positioning with companion ${companion.name}: ${surface.pitch} + their tagline vibe.`,
      source: "mixed",
    });
  }

  return out.slice(0, 16);
}
