-- Re-seed the central pool of 50 vibration patterns (idempotent).
-- Run in SQL Editor after migrations, or use to repair a partially empty pool.
-- Per-companion assignments are rebuilt by rarity via assign_vibration_patterns_for_companion (migration trigger / manual call).

INSERT INTO public.vibration_pattern_pool (pool_index, internal_label, payload, vibe_family) VALUES
(1, 'Feather Touch', '{"command":"vibrate","intensity":18,"duration":7000}'::jsonb, 'tease'),
(2, 'Slow Bloom', '{"command":"vibrate","intensity":22,"duration":9000}'::jsonb, 'tease'),
(3, 'Pulse Lite', '{"command":"pattern","pattern":"Pulse","intensity":50,"duration":8000}'::jsonb, 'tease'),
(4, 'Wave Tease', '{"command":"pattern","pattern":"Wave","intensity":50,"duration":10000}'::jsonb, 'tease'),
(5, 'Circle Draw', '{"command":"pattern","pattern":"Circle","intensity":50,"duration":9000}'::jsonb, 'tease'),
(6, 'Breath Sync', '{"command":"vibrate","intensity":28,"duration":12000}'::jsonb, 'tease'),
(7, 'Flutter', '{"command":"vibrate","intensity":25,"duration":6000}'::jsonb, 'tease'),
(8, 'Ripple', '{"command":"pattern","pattern":"ChaCha","intensity":50,"duration":8000}'::jsonb, 'tease'),
(9, 'Candle Flicker', '{"command":"vibrate","intensity":30,"duration":8000}'::jsonb, 'build'),
(10, 'Silk Drag', '{"command":"vibrate","intensity":32,"duration":9000}'::jsonb, 'build'),
(11, 'Tide In', '{"command":"pattern","pattern":"Wave","intensity":50,"duration":12000}'::jsonb, 'build'),
(12, 'Heat Rise', '{"command":"vibrate","intensity":38,"duration":8000}'::jsonb, 'build'),
(13, 'Spark Line', '{"command":"vibrate","intensity":40,"duration":7000}'::jsonb, 'build'),
(14, 'Glass Hum', '{"command":"vibrate","intensity":35,"duration":10000}'::jsonb, 'build'),
(15, 'Midnight Crawl', '{"command":"pattern","pattern":"Pulse","intensity":50,"duration":11000}'::jsonb, 'build'),
(16, 'Voltage Kiss', '{"command":"vibrate","intensity":45,"duration":6000}'::jsonb, 'build'),
(17, 'Copper Wire', '{"command":"vibrate","intensity":42,"duration":8000}'::jsonb, 'build'),
(18, 'Storm Front', '{"command":"pattern","pattern":"Fireworks","intensity":50,"duration":9000}'::jsonb, 'climax'),
(19, 'Redline', '{"command":"vibrate","intensity":72,"duration":5000}'::jsonb, 'climax'),
(20, 'Overload', '{"command":"vibrate","intensity":85,"duration":4500}'::jsonb, 'climax'),
(21, 'Earthquake Ride', '{"command":"pattern","pattern":"Earthquake","intensity":50,"duration":12000}'::jsonb, 'climax'),
(22, 'Nova Burst', '{"command":"pattern","pattern":"Fireworks","intensity":50,"duration":10000}'::jsonb, 'climax'),
(23, 'Edge Hold', '{"command":"vibrate","intensity":55,"duration":15000}'::jsonb, 'edge'),
(24, 'Denial Gate', '{"command":"vibrate","intensity":48,"duration":14000}'::jsonb, 'edge'),
(25, 'Stutter Peak', '{"command":"pattern","pattern":"Pulse","intensity":50,"duration":13000}'::jsonb, 'edge'),
(26, 'Cliff Hanger', '{"command":"vibrate","intensity":60,"duration":8000}'::jsonb, 'edge'),
(27, 'Afterglow', '{"command":"vibrate","intensity":22,"duration":14000}'::jsonb, 'aftercare'),
(28, 'Warm Towel', '{"command":"vibrate","intensity":20,"duration":16000}'::jsonb, 'aftercare'),
(29, 'Heartbeat Fade', '{"command":"pattern","pattern":"Pulse","intensity":50,"duration":15000}'::jsonb, 'aftercare'),
(30, 'Mist Settle', '{"command":"vibrate","intensity":24,"duration":12000}'::jsonb, 'aftercare'),
(31, 'Random Walk', '{"command":"pattern","pattern":"Random","intensity":50,"duration":10000}'::jsonb, 'build'),
(32, 'Roller Climb', '{"command":"pattern","pattern":"Wave","intensity":50,"duration":11000}'::jsonb, 'climax'),
(33, 'Echo Chamber', '{"command":"vibrate","intensity":50,"duration":9000}'::jsonb, 'build'),
(34, 'Neon Staccato', '{"command":"vibrate","intensity":58,"duration":6500}'::jsonb, 'climax'),
(35, 'Velvet Hammer', '{"command":"vibrate","intensity":68,"duration":5500}'::jsonb, 'climax'),
(36, 'Deep Coil', '{"command":"vibrate","intensity":52,"duration":10000}'::jsonb, 'build'),
(37, 'Satellite Orbit', '{"command":"pattern","pattern":"Circle","intensity":50,"duration":13000}'::jsonb, 'build'),
(38, 'Glitch Tease', '{"command":"vibrate","intensity":44,"duration":7000}'::jsonb, 'tease'),
(39, 'Chrome Surge', '{"command":"vibrate","intensity":62,"duration":6000}'::jsonb, 'climax'),
(40, 'Obsidian Drag', '{"command":"vibrate","intensity":36,"duration":11000}'::jsonb, 'edge'),
(41, 'Rose Thorn', '{"command":"vibrate","intensity":48,"duration":8000}'::jsonb, 'edge'),
(42, 'Midnight Train', '{"command":"pattern","pattern":"Wave","intensity":50,"duration":14000}'::jsonb, 'build'),
(43, 'Cryo Kiss', '{"command":"vibrate","intensity":28,"duration":9000}'::jsonb, 'tease'),
(44, 'Solar Flare', '{"command":"pattern","pattern":"Fireworks","intensity":50,"duration":8000}'::jsonb, 'climax'),
(45, 'Gravity Well', '{"command":"vibrate","intensity":75,"duration":5000}'::jsonb, 'climax'),
(46, 'Cipher Lock', '{"command":"vibrate","intensity":40,"duration":9000}'::jsonb, 'build'),
(47, 'Phantom Bite', '{"command":"vibrate","intensity":55,"duration":7500}'::jsonb, 'climax'),
(48, 'Hush Money', '{"command":"vibrate","intensity":26,"duration":13000}'::jsonb, 'aftercare'),
(49, 'Last Call', '{"command":"vibrate","intensity":65,"duration":4500}'::jsonb, 'climax'),
(50, 'Abyssal Signature Wave', '{"command":"pattern","pattern":"Earthquake","intensity":50,"duration":15000}'::jsonb, 'signature')
ON CONFLICT (pool_index) DO NOTHING;
