
ALTER TABLE public.custom_characters
  ADD COLUMN IF NOT EXISTS tagline text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS gender text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS orientation text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS role text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS tags text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS kinks text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS appearance text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS bio text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS system_prompt text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS fantasy_starters jsonb NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS gradient_from text NOT NULL DEFAULT '#7B2D8E',
  ADD COLUMN IF NOT EXISTS gradient_to text NOT NULL DEFAULT '#FF2D7B',
  ADD COLUMN IF NOT EXISTS image_url text,
  ADD COLUMN IF NOT EXISTS image_prompt text;
